// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: secretName
func (_m *Repository) Delete(secretName types.NamespacedName) error {
	ret := _m.Called(secretName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.NamespacedName) error); ok {
		r0 = rf(secretName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: name
func (_m *Repository) Exists(name types.NamespacedName) (bool, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(types.NamespacedName) (bool, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(types.NamespacedName) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(types.NamespacedName) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: name
func (_m *Repository) Get(name types.NamespacedName) (map[string][]byte, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 map[string][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(types.NamespacedName) (map[string][]byte, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(types.NamespacedName) map[string][]byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(types.NamespacedName) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertWithMerge provides a mock function with given fields: name, data
func (_m *Repository) UpsertWithMerge(name types.NamespacedName, data map[string][]byte) error {
	ret := _m.Called(name, data)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWithMerge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.NamespacedName, map[string][]byte) error); ok {
		r0 = rf(name, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertWithReplace provides a mock function with given fields: name, data
func (_m *Repository) UpsertWithReplace(name types.NamespacedName, data map[string][]byte) error {
	ret := _m.Called(name, data)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWithReplace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.NamespacedName, map[string][]byte) error); ok {
		r0 = rf(name, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
