// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	config "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// GetConnectionConfig provides a mock function with no fields
func (_m *Provider) GetConnectionConfig() (config.ConnectionConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionConfig")
	}

	var r0 config.ConnectionConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (config.ConnectionConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() config.ConnectionConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.ConnectionConfig)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRuntimeConfig provides a mock function with no fields
func (_m *Provider) GetRuntimeConfig() (config.RuntimeConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRuntimeConfig")
	}

	var r0 config.RuntimeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (config.RuntimeConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() config.RuntimeConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.RuntimeConfig)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
