// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	oauth "github.com/kyma-project/application-connector-manager/tests/test/compass-runtime-agent/testkit/oauth"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetAuthorizationToken provides a mock function with no fields
func (_m *Client) GetAuthorizationToken() (oauth.Token, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationToken")
	}

	var r0 oauth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func() (oauth.Token, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() oauth.Token); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(oauth.Token)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
