# -*- mode: Makefile -*-

NAMESPACE ?= test
GOPATH ?= $(shell go env GOPATH)

VALIDATOR_TEST_IMAGE = "$(DOCKER_PUSH_REPOSITORY)$(DOCKER_PUSH_DIRECTORY)/connectivity-validator-test:$(DOCKER_TAG)"
TEST_TIMEOUT = "3m"
MAKEFILE_NAME=Makefile.test-application-conn-validator
TEST_LOG = ${PWD}/application-connector-validator-test.log

test: test-validator

.PHONY: patch-validator
patch-validator:
	yq e -i '. |= (select(.kind == "Deployment" and .metadata.name == "central-application-connectivity-validator") | .spec.template.spec.containers[0].args[5] = "--eventingPublisherHost=echoserver.test.svc.cluster.local" | .spec.template.spec.containers[0].args[6] = "--eventingDestinationPath=/anything/rewrite" | .spec.template.metadata.annotations.["traffic.sidecar.istio.io/excludeInboundPorts"] += "8080")' ${PWD}/application-connector.yaml

.PHONY: test-validator
test-validator: patch-validator create-resources
	@echo "::group::test-validator"
	kubectl wait --for=condition=complete --timeout=$(TEST_TIMEOUT) -n $(NAMESPACE) job/application-connectivity-validator-test; \
		kubectl -n $(NAMESPACE) -l batch.kubernetes.io/job-name=application-gateway-test logs 2>&1 > $(TEST_LOG)
	@echo "::endgroup::"

.PHONY: create-resources
create-resources:
	@echo "::group::create-test-namespace"
	kubectl create namespace $(NAMESPACE) --dry-run=client -o yaml \
		| kubectl apply -f -
	kubectl label namespace $(NAMESPACE) istio-injection=enabled --overwrite
	@echo "::endgroup::"
	@echo "::group::create-resources::install-echoserver"
	@helm template ${PWD}/tests/resources/charts/application-connectivity-validator-test/charts/echoserver \
		--set global.namespace=$(NAMESPACE) \
		| kubectl apply -f -
	kubectl rollout status deployment echoserver -n test --timeout=90s
	@echo "::endgroup::"
	@echo "::group::create-resources::install-test"
	@helm template ${PWD}/tests/resources/charts/application-connectivity-validator-test/charts/test \
    		--set namespace=$(NAMESPACE) \
    		--values ${PWD}/tests/resources/charts/application-connectivity-validator-test/values.yaml \
		| kubectl apply -f -
	@echo "::endgroup::"

