// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AssignApplicationToFormation provides a mock function with given fields: appId, formationName
func (_m *Client) AssignApplicationToFormation(appId string, formationName string) error {
	ret := _m.Called(appId, formationName)

	if len(ret) == 0 {
		panic("no return value specified for AssignApplicationToFormation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(appId, formationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignRuntimeToFormation provides a mock function with given fields: runtimeId, formationName
func (_m *Client) AssignRuntimeToFormation(runtimeId string, formationName string) error {
	ret := _m.Called(runtimeId, formationName)

	if len(ret) == 0 {
		panic("no return value specified for AssignRuntimeToFormation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(runtimeId, formationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConnectionToken provides a mock function with given fields: runtimeID
func (_m *Client) GetConnectionToken(runtimeID string) (string, string, error) {
	ret := _m.Called(runtimeID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(runtimeID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(runtimeID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(runtimeID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(runtimeID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterApplication provides a mock function with given fields: appName, displayName
func (_m *Client) RegisterApplication(appName string, displayName string) (string, error) {
	ret := _m.Called(appName, displayName)

	if len(ret) == 0 {
		panic("no return value specified for RegisterApplication")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(appName, displayName)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(appName, displayName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(appName, displayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterFormation provides a mock function with given fields: formationName
func (_m *Client) RegisterFormation(formationName string) error {
	ret := _m.Called(formationName)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFormation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(formationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterRuntime provides a mock function with given fields: runtimeName
func (_m *Client) RegisterRuntime(runtimeName string) (string, error) {
	ret := _m.Called(runtimeName)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRuntime")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(runtimeName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(runtimeName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runtimeName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnassignApplication provides a mock function with given fields: appId, formationName
func (_m *Client) UnassignApplication(appId string, formationName string) error {
	ret := _m.Called(appId, formationName)

	if len(ret) == 0 {
		panic("no return value specified for UnassignApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(appId, formationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnregisterApplication provides a mock function with given fields: id
func (_m *Client) UnregisterApplication(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnregisterFormation provides a mock function with given fields: formationName
func (_m *Client) UnregisterFormation(formationName string) error {
	ret := _m.Called(formationName)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterFormation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(formationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnregisterRuntime provides a mock function with given fields: id
func (_m *Client) UnregisterRuntime(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterRuntime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateApplication provides a mock function with given fields: id, newDesc
func (_m *Client) UpdateApplication(id string, newDesc string) (string, error) {
	ret := _m.Called(id, newDesc)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplication")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(id, newDesc)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(id, newDesc)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, newDesc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
