// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/apperrors"
	applications "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/applications"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/model"

	types "k8s.io/apimachinery/pkg/types"
)

// CredentialsService is an autogenerated mock type for the CredentialsService type
type CredentialsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: application, appUID, bundleID, credentials
func (_m *CredentialsService) Create(application string, appUID types.UID, bundleID string, credentials *model.Credentials) (applications.Credentials, apperrors.AppError) {
	ret := _m.Called(application, appUID, bundleID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 applications.Credentials
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, types.UID, string, *model.Credentials) (applications.Credentials, apperrors.AppError)); ok {
		return rf(application, appUID, bundleID, credentials)
	}
	if rf, ok := ret.Get(0).(func(string, types.UID, string, *model.Credentials) applications.Credentials); ok {
		r0 = rf(application, appUID, bundleID, credentials)
	} else {
		r0 = ret.Get(0).(applications.Credentials)
	}

	if rf, ok := ret.Get(1).(func(string, types.UID, string, *model.Credentials) apperrors.AppError); ok {
		r1 = rf(application, appUID, bundleID, credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name
func (_m *CredentialsService) Delete(name string) apperrors.AppError {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) apperrors.AppError); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Get provides a mock function with given fields: application, credentials
func (_m *CredentialsService) Get(application string, credentials applications.Credentials) (model.Credentials, apperrors.AppError) {
	ret := _m.Called(application, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Credentials
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, applications.Credentials) (model.Credentials, apperrors.AppError)); ok {
		return rf(application, credentials)
	}
	if rf, ok := ret.Get(0).(func(string, applications.Credentials) model.Credentials); ok {
		r0 = rf(application, credentials)
	} else {
		r0 = ret.Get(0).(model.Credentials)
	}

	if rf, ok := ret.Get(1).(func(string, applications.Credentials) apperrors.AppError); ok {
		r1 = rf(application, credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: application, appUID, bundleID, credentials
func (_m *CredentialsService) Upsert(application string, appUID types.UID, bundleID string, credentials *model.Credentials) (applications.Credentials, apperrors.AppError) {
	ret := _m.Called(application, appUID, bundleID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 applications.Credentials
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, types.UID, string, *model.Credentials) (applications.Credentials, apperrors.AppError)); ok {
		return rf(application, appUID, bundleID, credentials)
	}
	if rf, ok := ret.Get(0).(func(string, types.UID, string, *model.Credentials) applications.Credentials); ok {
		r0 = rf(application, appUID, bundleID, credentials)
	} else {
		r0 = ret.Get(0).(applications.Credentials)
	}

	if rf, ok := ret.Get(1).(func(string, types.UID, string, *model.Credentials) apperrors.AppError); ok {
		r1 = rf(application, appUID, bundleID, credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// NewCredentialsService creates a new instance of CredentialsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsService {
	mock := &CredentialsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
