// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/apperrors"

	mock "github.com/stretchr/testify/mock"

	strategy "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/secrets/strategy"

	types "k8s.io/apimachinery/pkg/types"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: application, appUID, name, bundleID, data
func (_m *Repository) Create(application string, appUID types.UID, name string, bundleID string, data strategy.SecretData) apperrors.AppError {
	ret := _m.Called(application, appUID, name, bundleID, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, types.UID, string, string, strategy.SecretData) apperrors.AppError); ok {
		r0 = rf(application, appUID, name, bundleID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: name
func (_m *Repository) Delete(name string) apperrors.AppError {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) apperrors.AppError); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Get provides a mock function with given fields: name
func (_m *Repository) Get(name string) (strategy.SecretData, apperrors.AppError) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 strategy.SecretData
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) (strategy.SecretData, apperrors.AppError)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) strategy.SecretData); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.SecretData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: application, appUID, name, bundleID, data
func (_m *Repository) Upsert(application string, appUID types.UID, name string, bundleID string, data strategy.SecretData) apperrors.AppError {
	ret := _m.Called(application, appUID, name, bundleID, data)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, types.UID, string, string, strategy.SecretData) apperrors.AppError); ok {
		r0 = rf(application, appUID, name, bundleID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
