// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	externalschema "github.com/kyma-incubator/compass/components/connector/pkg/graphql/externalschema"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Configuration provides a mock function with given fields: ctx, headers
func (_m *Client) Configuration(ctx context.Context, headers map[string]string) (externalschema.Configuration, error) {
	ret := _m.Called(ctx, headers)

	if len(ret) == 0 {
		panic("no return value specified for Configuration")
	}

	var r0 externalschema.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (externalschema.Configuration, error)); ok {
		return rf(ctx, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) externalschema.Configuration); ok {
		r0 = rf(ctx, headers)
	} else {
		r0 = ret.Get(0).(externalschema.Configuration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignCSR provides a mock function with given fields: ctx, csr, headers
func (_m *Client) SignCSR(ctx context.Context, csr string, headers map[string]string) (externalschema.CertificationResult, error) {
	ret := _m.Called(ctx, csr, headers)

	if len(ret) == 0 {
		panic("no return value specified for SignCSR")
	}

	var r0 externalschema.CertificationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (externalschema.CertificationResult, error)); ok {
		return rf(ctx, csr, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) externalschema.CertificationResult); ok {
		r0 = rf(ctx, csr, headers)
	} else {
		r0 = ret.Get(0).(externalschema.CertificationResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, csr, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
