// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	pkix "crypto/x509/pkix"

	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"
)

// CSRProvider is an autogenerated mock type for the CSRProvider type
type CSRProvider struct {
	mock.Mock
}

// CreateCSR provides a mock function with given fields: subject
func (_m *CSRProvider) CreateCSR(subject pkix.Name) (string, *rsa.PrivateKey, error) {
	ret := _m.Called(subject)

	if len(ret) == 0 {
		panic("no return value specified for CreateCSR")
	}

	var r0 string
	var r1 *rsa.PrivateKey
	var r2 error
	if rf, ok := ret.Get(0).(func(pkix.Name) (string, *rsa.PrivateKey, error)); ok {
		return rf(subject)
	}
	if rf, ok := ret.Get(0).(func(pkix.Name) string); ok {
		r0 = rf(subject)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(pkix.Name) *rsa.PrivateKey); ok {
		r1 = rf(subject)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*rsa.PrivateKey)
		}
	}

	if rf, ok := ret.Get(2).(func(pkix.Name) error); ok {
		r2 = rf(subject)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewCSRProvider creates a new instance of CSRProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCSRProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CSRProvider {
	mock := &CSRProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
