// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	certificates "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/certificates"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// CredentialsExist provides a mock function with no fields
func (_m *Manager) CredentialsExist() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialsExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClientCredentials provides a mock function with no fields
func (_m *Manager) GetClientCredentials() (certificates.ClientCredentials, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientCredentials")
	}

	var r0 certificates.ClientCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func() (certificates.ClientCredentials, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() certificates.ClientCredentials); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(certificates.ClientCredentials)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreserveCredentials provides a mock function with given fields: _a0
func (_m *Manager) PreserveCredentials(_a0 certificates.Credentials) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for PreserveCredentials")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(certificates.Credentials) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
