// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	types "github.com/kyma-project/application-connector-manager/tests/test/compass-runtime-agent/testkit/init/types"
	mock "github.com/stretchr/testify/mock"
)

// CertificateSecretConfigurator is an autogenerated mock type for the CertificateSecretConfigurator type
type CertificateSecretConfigurator struct {
	mock.Mock
}

// Do provides a mock function with given fields: caSecretName, clusterCertSecretName
func (_m *CertificateSecretConfigurator) Do(caSecretName string, clusterCertSecretName string) (types.RollbackFunc, error) {
	ret := _m.Called(caSecretName, clusterCertSecretName)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 types.RollbackFunc
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (types.RollbackFunc, error)); ok {
		return rf(caSecretName, clusterCertSecretName)
	}
	if rf, ok := ret.Get(0).(func(string, string) types.RollbackFunc); ok {
		r0 = rf(caSecretName, clusterCertSecretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.RollbackFunc)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(caSecretName, clusterCertSecretName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCertificateSecretConfigurator creates a new instance of CertificateSecretConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateSecretConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateSecretConfigurator {
	mock := &CertificateSecretConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
