// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	types "github.com/kyma-project/application-connector-manager/tests/test/compass-runtime-agent/testkit/init/types"
	mock "github.com/stretchr/testify/mock"
)

// CompassConnectionConfigurator is an autogenerated mock type for the CompassConnectionConfigurator type
type CompassConnectionConfigurator struct {
	mock.Mock
}

// Do provides a mock function with no fields
func (_m *CompassConnectionConfigurator) Do() (types.RollbackFunc, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 types.RollbackFunc
	var r1 error
	if rf, ok := ret.Get(0).(func() (types.RollbackFunc, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() types.RollbackFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.RollbackFunc)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCompassConnectionConfigurator creates a new instance of CompassConnectionConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompassConnectionConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompassConnectionConfigurator {
	mock := &CompassConnectionConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
