// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	v1alpha1 "github.com/kyma-project/application-connector-manager/components/central-application-gateway/pkg/apis/applicationconnector/v1alpha1"
	model "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/model"
	mock "github.com/stretchr/testify/mock"
)

// Converter is an autogenerated mock type for the Converter type
type Converter struct {
	mock.Mock
}

// Do provides a mock function with given fields: application
func (_m *Converter) Do(application model.Application) v1alpha1.Application {
	ret := _m.Called(application)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 v1alpha1.Application
	if rf, ok := ret.Get(0).(func(model.Application) v1alpha1.Application); ok {
		r0 = rf(application)
	} else {
		r0 = ret.Get(0).(v1alpha1.Application)
	}

	return r0
}

// NewConverter creates a new instance of Converter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Converter {
	mock := &Converter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
