//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppConnValidatorSpec) DeepCopyInto(out *AppConnValidatorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnValidatorSpec.
func (in *AppConnValidatorSpec) DeepCopy() *AppConnValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(AppConnValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGatewaySpec) DeepCopyInto(out *AppGatewaySpec) {
	*out = *in
	out.ProxyTimeout = in.ProxyTimeout
	out.RequestTimeout = in.RequestTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGatewaySpec.
func (in *AppGatewaySpec) DeepCopy() *AppGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(AppGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConnector) DeepCopyInto(out *ApplicationConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConnector.
func (in *ApplicationConnector) DeepCopy() *ApplicationConnector {
	if in == nil {
		return nil
	}
	out := new(ApplicationConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConnectorList) DeepCopyInto(out *ApplicationConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConnectorList.
func (in *ApplicationConnectorList) DeepCopy() *ApplicationConnectorList {
	if in == nil {
		return nil
	}
	out := new(ApplicationConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConnectorSpec) DeepCopyInto(out *ApplicationConnectorSpec) {
	*out = *in
	out.ApplicationGatewaySpec = in.ApplicationGatewaySpec
	out.AppConValidatorSpec = in.AppConValidatorSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConnectorSpec.
func (in *ApplicationConnectorSpec) DeepCopy() *ApplicationConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeAgentSpec) DeepCopyInto(out *RuntimeAgentSpec) {
	*out = *in
	out.ControllerSyncPeriod = in.ControllerSyncPeriod
	out.MinConfigSyncTime = in.MinConfigSyncTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeAgentSpec.
func (in *RuntimeAgentSpec) DeepCopy() *RuntimeAgentSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}
