// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	certificates "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/certificates"
	compassconnection "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/compassconnection"

	context "context"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/pkg/apis/compass/v1alpha1"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

// EstablishConnection provides a mock function with given fields: ctx, connectorURL, token
func (_m *Connector) EstablishConnection(ctx context.Context, connectorURL string, token string) (compassconnection.EstablishedConnection, error) {
	ret := _m.Called(ctx, connectorURL, token)

	if len(ret) == 0 {
		panic("no return value specified for EstablishConnection")
	}

	var r0 compassconnection.EstablishedConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (compassconnection.EstablishedConnection, error)); ok {
		return rf(ctx, connectorURL, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) compassconnection.EstablishedConnection); ok {
		r0 = rf(ctx, connectorURL, token)
	} else {
		r0 = ret.Get(0).(compassconnection.EstablishedConnection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, connectorURL, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintainConnection provides a mock function with given fields: ctx, renewCert, credentialsExist
func (_m *Connector) MaintainConnection(ctx context.Context, renewCert bool, credentialsExist bool) (*certificates.Credentials, v1alpha1.ManagementInfo, error) {
	ret := _m.Called(ctx, renewCert, credentialsExist)

	if len(ret) == 0 {
		panic("no return value specified for MaintainConnection")
	}

	var r0 *certificates.Credentials
	var r1 v1alpha1.ManagementInfo
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, bool) (*certificates.Credentials, v1alpha1.ManagementInfo, error)); ok {
		return rf(ctx, renewCert, credentialsExist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool, bool) *certificates.Credentials); ok {
		r0 = rf(ctx, renewCert, credentialsExist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool, bool) v1alpha1.ManagementInfo); ok {
		r1 = rf(ctx, renewCert, credentialsExist)
	} else {
		r1 = ret.Get(1).(v1alpha1.ManagementInfo)
	}

	if rf, ok := ret.Get(2).(func(context.Context, bool, bool) error); ok {
		r2 = rf(ctx, renewCert, credentialsExist)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
