// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha1 "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/pkg/apis/compass/v1alpha1"
)

// CRManager is an autogenerated mock type for the CRManager type
type CRManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cc, options
func (_m *CRManager) Create(ctx context.Context, cc *v1alpha1.CompassConnection, options v1.CreateOptions) (*v1alpha1.CompassConnection, error) {
	ret := _m.Called(ctx, cc, options)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1alpha1.CompassConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection, v1.CreateOptions) (*v1alpha1.CompassConnection, error)); ok {
		return rf(ctx, cc, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection, v1.CreateOptions) *v1alpha1.CompassConnection); ok {
		r0 = rf(ctx, cc, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CompassConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.CompassConnection, v1.CreateOptions) error); ok {
		r1 = rf(ctx, cc, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, name, options
func (_m *CRManager) Delete(ctx context.Context, name string, options v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, name, options
func (_m *CRManager) Get(ctx context.Context, name string, options v1.GetOptions) (*v1alpha1.CompassConnection, error) {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha1.CompassConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*v1alpha1.CompassConnection, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v1alpha1.CompassConnection); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CompassConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, cc, options
func (_m *CRManager) Update(ctx context.Context, cc *v1alpha1.CompassConnection, options v1.UpdateOptions) (*v1alpha1.CompassConnection, error) {
	ret := _m.Called(ctx, cc, options)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1alpha1.CompassConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection, v1.UpdateOptions) (*v1alpha1.CompassConnection, error)); ok {
		return rf(ctx, cc, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection, v1.UpdateOptions) *v1alpha1.CompassConnection); ok {
		r0 = rf(ctx, cc, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CompassConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.CompassConnection, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, cc, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCRManager creates a new instance of CRManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCRManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *CRManager {
	mock := &CRManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
