// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	v1alpha1 "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/pkg/apis/compass/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// Supervisor is an autogenerated mock type for the Supervisor type
type Supervisor struct {
	mock.Mock
}

// InitializeCompassConnection provides a mock function with given fields: ctx
func (_m *Supervisor) InitializeCompassConnection(ctx context.Context) (*v1alpha1.CompassConnection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeCompassConnection")
	}

	var r0 *v1alpha1.CompassConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v1alpha1.CompassConnection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v1alpha1.CompassConnection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CompassConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintainCompassConnection provides a mock function with given fields: ctx, connection
func (_m *Supervisor) MaintainCompassConnection(ctx context.Context, connection *v1alpha1.CompassConnection) error {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for MaintainCompassConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection) error); ok {
		r0 = rf(ctx, connection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SynchronizeWithCompass provides a mock function with given fields: ctx, connection
func (_m *Supervisor) SynchronizeWithCompass(ctx context.Context, connection *v1alpha1.CompassConnection) (*v1alpha1.CompassConnection, error) {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for SynchronizeWithCompass")
	}

	var r0 *v1alpha1.CompassConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection) (*v1alpha1.CompassConnection, error)); ok {
		return rf(ctx, connection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.CompassConnection) *v1alpha1.CompassConnection); ok {
		r0 = rf(ctx, connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CompassConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.CompassConnection) error); ok {
		r1 = rf(ctx, connection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSupervisor creates a new instance of Supervisor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupervisor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Supervisor {
	mock := &Supervisor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
