// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1beta1 "k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1"
)

// MetricsV1beta1Interface is an autogenerated mock type for the MetricsV1beta1Interface type
type MetricsV1beta1Interface struct {
	mock.Mock
}

// NodeMetricses provides a mock function with no fields
func (_m *MetricsV1beta1Interface) NodeMetricses() v1beta1.NodeMetricsInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeMetricses")
	}

	var r0 v1beta1.NodeMetricsInterface
	if rf, ok := ret.Get(0).(func() v1beta1.NodeMetricsInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.NodeMetricsInterface)
		}
	}

	return r0
}

// PodMetricses provides a mock function with given fields: namespace
func (_m *MetricsV1beta1Interface) PodMetricses(namespace string) v1beta1.PodMetricsInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for PodMetricses")
	}

	var r0 v1beta1.PodMetricsInterface
	if rf, ok := ret.Get(0).(func(string) v1beta1.PodMetricsInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.PodMetricsInterface)
		}
	}

	return r0
}

// RESTClient provides a mock function with no fields
func (_m *MetricsV1beta1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// NewMetricsV1beta1Interface creates a new instance of MetricsV1beta1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsV1beta1Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsV1beta1Interface {
	mock := &MetricsV1beta1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
