// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	discovery "k8s.io/client-go/discovery"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1"

	v1beta1 "k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1"
)

// MetricsClientsetInterface is an autogenerated mock type for the MetricsClientsetInterface type
type MetricsClientsetInterface struct {
	mock.Mock
}

// Discovery provides a mock function with no fields
func (_m *MetricsClientsetInterface) Discovery() discovery.DiscoveryInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Discovery")
	}

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}

// MetricsV1alpha1 provides a mock function with no fields
func (_m *MetricsClientsetInterface) MetricsV1alpha1() v1alpha1.MetricsV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MetricsV1alpha1")
	}

	var r0 v1alpha1.MetricsV1alpha1Interface
	if rf, ok := ret.Get(0).(func() v1alpha1.MetricsV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.MetricsV1alpha1Interface)
		}
	}

	return r0
}

// MetricsV1beta1 provides a mock function with no fields
func (_m *MetricsClientsetInterface) MetricsV1beta1() v1beta1.MetricsV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MetricsV1beta1")
	}

	var r0 v1beta1.MetricsV1beta1Interface
	if rf, ok := ret.Get(0).(func() v1beta1.MetricsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.MetricsV1beta1Interface)
		}
	}

	return r0
}

// NewMetricsClientsetInterface creates a new instance of MetricsClientsetInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsClientsetInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsClientsetInterface {
	mock := &MetricsClientsetInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
