// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/apperrors"
	applications "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/applications"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/model"

	strategy "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/secrets/strategy"
)

// AccessStrategy is an autogenerated mock type for the AccessStrategy type
type AccessStrategy struct {
	mock.Mock
}

// ToCredentials provides a mock function with given fields: secretData, appCredentials
func (_m *AccessStrategy) ToCredentials(secretData strategy.SecretData, appCredentials *applications.Credentials) (model.Credentials, apperrors.AppError) {
	ret := _m.Called(secretData, appCredentials)

	if len(ret) == 0 {
		panic("no return value specified for ToCredentials")
	}

	var r0 model.Credentials
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(strategy.SecretData, *applications.Credentials) (model.Credentials, apperrors.AppError)); ok {
		return rf(secretData, appCredentials)
	}
	if rf, ok := ret.Get(0).(func(strategy.SecretData, *applications.Credentials) model.Credentials); ok {
		r0 = rf(secretData, appCredentials)
	} else {
		r0 = ret.Get(0).(model.Credentials)
	}

	if rf, ok := ret.Get(1).(func(strategy.SecretData, *applications.Credentials) apperrors.AppError); ok {
		r1 = rf(secretData, appCredentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// NewAccessStrategy creates a new instance of AccessStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessStrategy {
	mock := &AccessStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
