// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/apperrors"
	applications "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/applications"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/model"

	strategy "github.com/kyma-project/application-connector-manager/components/compass-runtime-agent/internal/kyma/secrets/strategy"
)

// ModificationStrategy is an autogenerated mock type for the ModificationStrategy type
type ModificationStrategy struct {
	mock.Mock
}

// CreateSecretData provides a mock function with given fields: credentials
func (_m *ModificationStrategy) CreateSecretData(credentials *model.Credentials) (strategy.SecretData, apperrors.AppError) {
	ret := _m.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecretData")
	}

	var r0 strategy.SecretData
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(*model.Credentials) (strategy.SecretData, apperrors.AppError)); ok {
		return rf(credentials)
	}
	if rf, ok := ret.Get(0).(func(*model.Credentials) strategy.SecretData); ok {
		r0 = rf(credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.SecretData)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Credentials) apperrors.AppError); ok {
		r1 = rf(credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// CredentialsProvided provides a mock function with given fields: credentials
func (_m *ModificationStrategy) CredentialsProvided(credentials *model.Credentials) bool {
	ret := _m.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for CredentialsProvided")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*model.Credentials) bool); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ShouldUpdate provides a mock function with given fields: currentData, newData
func (_m *ModificationStrategy) ShouldUpdate(currentData strategy.SecretData, newData strategy.SecretData) bool {
	ret := _m.Called(currentData, newData)

	if len(ret) == 0 {
		panic("no return value specified for ShouldUpdate")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(strategy.SecretData, strategy.SecretData) bool); ok {
		r0 = rf(currentData, newData)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ToCredentialsInfo provides a mock function with given fields: credentials, secretName
func (_m *ModificationStrategy) ToCredentialsInfo(credentials *model.Credentials, secretName string) applications.Credentials {
	ret := _m.Called(credentials, secretName)

	if len(ret) == 0 {
		panic("no return value specified for ToCredentialsInfo")
	}

	var r0 applications.Credentials
	if rf, ok := ret.Get(0).(func(*model.Credentials, string) applications.Credentials); ok {
		r0 = rf(credentials, secretName)
	} else {
		r0 = ret.Get(0).(applications.Credentials)
	}

	return r0
}

// NewModificationStrategy creates a new instance of ModificationStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModificationStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModificationStrategy {
	mock := &ModificationStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
