// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NameResolver is an autogenerated mock type for the NameResolver type
type NameResolver struct {
	mock.Mock
}

// GetCredentialsSecretName provides a mock function with given fields: application, bundleID
func (_m *NameResolver) GetCredentialsSecretName(application string, bundleID string) string {
	ret := _m.Called(application, bundleID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialsSecretName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(application, bundleID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRequestParametersSecretName provides a mock function with given fields: application, bundleID
func (_m *NameResolver) GetRequestParametersSecretName(application string, bundleID string) string {
	ret := _m.Called(application, bundleID)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestParametersSecretName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(application, bundleID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewNameResolver creates a new instance of NameResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNameResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *NameResolver {
	mock := &NameResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
